name: 💡 Feature Request
description: Suggest an idea or improvement for this plugin
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!  
        Please fill out the details below so we can better understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like the plugin to do?
      placeholder: "I would like if the plugin could ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Alternative approaches are ..."
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or mockups here.
      placeholder: "Any additional notes ..."
